### ISSUE TITLE
Missing lib folder in npm package

### ISSUE THREAD

**Issue by austencm** [mdedys/react-text-trimmer#13]
Tried importing this package via Webpack and hitting this error:

```
Module not found: Error: Can't resolve './lib/trimmer.js' in '{...}/node_modules/react-text-trimmer'
```

The index file seems to be trying to require a file that isn't there. Is this an issue with the npm package, or am I doing something wrong?

![screen shot 2018-02-20 at 4 35 19 pm](https://user-images.githubusercontent.com/6107869/36456893-20f6ac1c-165c-11e8-894c-5776b92fed54.png)

**Comment by larsfoll** [comment]
Same issue, the trimmer.js is located in the ./src folder not in the ./lib folder

**Comment by mdedys** [comment]
No longer applicable to newest version.
